services:
  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
    environment:
      TZ: ${PIHOLE_TZ}
      WEBPASSWORD: ${PIHOLE_PASSWORD}
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    expose:
      - 80
    networks:
      - default
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`${PIHOLE_URL}`)"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"

networks:
  default:
  proxy-network:
    external: true
