services:
  pihole:
    image: pihole/pihole:2025.07.1
    restart: unless-stopped
    environment:
      TZ: ${PIHOLE_TZ}
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
      FTLCONF_dns_upstreams: unbound#5335;fd00:fa17:d3ad:c0d3::5335#5335
      FTLCONF_misc_etc_dnsmasq_d: 'true'
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    expose:
      - 80
    networks:
      - default
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`${PIHOLE_URL}`)"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    dns:
      - 127.0.0.1

  unbound:
    image: klutchell/unbound:1.23.1
    restart: unless-stopped
    volumes:
      - ./unbound:/etc/unbound/custom.conf.d
    expose:
      - "5335/tcp"
      - "5335/udp"
    networks:
      default:
        ipv6_address: fd00:fa17:d3ad:c0d3::5335

networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd00:fa17:d3ad:c0d3::/64
  proxy-network:
    external: true
